#ifndef __NVSCENE_STATS2__
#define __NVSCENE_STATS2__

#ifdef NX_ENABLE_SCENE_STATS2
#define NX_ENABLE_COMPARTMENT_STATS
#endif

enum SceneStatisticEnum
{
	StatActivePairs,
	StatTotalPairs,
	//	StatActiveFastPairs,
	//	StatTotalFastPairs,
	StatTotalFilteredPairs,
	StatActiveContactNotificationPairs,
	StatTotalContactNotificationPairs,
	StatActiveContactModificationPairs,
	StatTotalContactModificationPairs,

	StatTotalContacts,
	StatTotalActorsInAwakeGroups,

	StatTotalActors,
	StatActiveDynamicActors,
	StatTotalDynamicActors,
	StatActiveCompoundActors,
	StatTotalCompoundActors,
	StatActiveCompoundActors3Plus,
	StatTotalCompoundActors3Plus,
	StatActiveCompoundActors10Plus,
	StatTotalCompoundActors10Plus,
	StatTotalKinematicActors,
	//StatMovedKinematicActors,

	StatTotalShapes,

	StatTotalStaticShapes,
	//StatMovedStaticShapes,
	StatTotalMirroredShapes,
	StatActiveDynamicShapes,
	StatTotalDynamicShapes,
	StatActiveTriggerShapes,
	StatTotalTriggerShapes,
	//StatActiveCCDEnabledShapes,
	StatTotalCCDEnabledShapes,
	//StatActiveAnisotropicFrictionShapes,
	//StatTotalAnisotropicFrictionShapes,

	StatActiveBoxShapes,
	StatTotalBoxShapes,
	StatActiveSphereShapes,
	StatTotalSphereShapes,
	StatActiveCapsuleShapes,
	StatTotalCapsuleShapes,
	StatActiveConvexShapes,
	StatTotalConvexShapes,
	StatActiveBigConvexShapes,
	StatTotalBigConvexShapes,
	StatActiveWheelShapes,
	StatTotalWheelShapes,
	StatActiveHeightfieldShapes,
	StatTotalHeightfieldShapes,
	StatActivePlaneShapes,
	StatTotalPlaneShapes,
	StatActiveTriMeshShapes,
	StatTotalTriMeshShapes,

	StatActiveColliders,

	StatActiveSwBoxBoxColliders,
	StatActiveSwBoxSphereColliders,
	StatActiveSwBoxCapsuleColliders,
	StatActiveSwBoxConvexColliders,
	StatActiveSwBoxWheelColliders,
	StatActiveSwBoxPlaneColliders,
	StatActiveSwBoxHeightfieldColliders,
	StatActiveSwBoxTriMeshColliders,
	StatActiveSwSphereSphereColliders,
	StatActiveSwSphereCapsuleColliders,
	StatActiveSwSphereConvexColliders,
	StatActiveSwSphereWheelColliders,
	StatActiveSwSpherePlaneColliders,
	StatActiveSwSphereHeightfieldColliders,
	StatActiveSwSphereTriMeshColliders,
	StatActiveSwCapsuleCapsuleColliders,
	StatActiveSwCapsuleConvexColliders,
	StatActiveSwCapsuleWheelColliders,
	StatActiveSwCapsulePlaneColliders,
	StatActiveSwCapsuleHeightfieldColliders,
	StatActiveSwCapsuleTriMeshColliders,
	StatActiveSwConvexConvexColliders,
	StatActiveSwConvexWheelColliders,
	StatActiveSwConvexPlaneColliders,
	StatActiveSwConvexHeightfieldColliders,
	StatActiveSwConvexTriMeshColliders,
	StatActiveSwWheelWheelColliders,
	StatActiveSwWheelPlaneColliders,
	StatActiveSwWheelHeightfieldColliders,
	StatActiveSwWheelTriMeshColliders,

	StatActiveHwBoxBoxColliders,
	StatActiveHwBoxSphereColliders,
	StatActiveHwBoxCapsuleColliders,
	StatActiveHwBoxConvexColliders,
	StatActiveHwBoxWheelColliders,
	StatActiveHwBoxPlaneColliders,
	StatActiveHwBoxHeightfieldColliders,
	StatActiveHwBoxTriMeshColliders,
	StatActiveHwSphereSphereColliders,
	StatActiveHwSphereCapsuleColliders,
	StatActiveHwSphereConvexColliders,
	StatActiveHwSphereWheelColliders,
	StatActiveHwSpherePlaneColliders,
	StatActiveHwSphereHeightfieldColliders,
	StatActiveHwSphereTriMeshColliders,
	StatActiveHwCapsuleCapsuleColliders,
	StatActiveHwCapsuleConvexColliders,
	StatActiveHwCapsuleWheelColliders,
	StatActiveHwCapsulePlaneColliders,
	StatActiveHwCapsuleHeightfieldColliders,
	StatActiveHwCapsuleTriMeshColliders,
	StatActiveHwConvexConvexColliders,
	StatActiveHwConvexWheelColliders,
	StatActiveHwConvexPlaneColliders,
	StatActiveHwConvexHeightfieldColliders,
	StatActiveHwConvexTriMeshColliders,
	StatActiveHwWheelWheelColliders,
	StatActiveHwWheelPlaneColliders,
	StatActiveHwWheelHeightfieldColliders,
	StatActiveHwWheelTriMeshColliders,

	StatTotalColliders, 
	StatSwForcedColliders, 

	StatTotalSwBoxBoxColliders,
	StatTotalSwBoxSphereColliders,
	StatTotalSwBoxCapsuleColliders,
	StatTotalSwBoxConvexColliders,
	StatTotalSwBoxWheelColliders,
	StatTotalSwBoxPlaneColliders,
	StatTotalSwBoxHeightfieldColliders,
	StatTotalSwBoxTriMeshColliders,
	StatTotalSwSphereSphereColliders,
	StatTotalSwSphereCapsuleColliders,
	StatTotalSwSphereConvexColliders,
	StatTotalSwSphereWheelColliders,
	StatTotalSwSpherePlaneColliders,
	StatTotalSwSphereHeightfieldColliders,
	StatTotalSwSphereTriMeshColliders,
	StatTotalSwCapsuleCapsuleColliders,
	StatTotalSwCapsuleConvexColliders,
	StatTotalSwCapsuleWheelColliders,
	StatTotalSwCapsulePlaneColliders,
	StatTotalSwCapsuleHeightfieldColliders,
	StatTotalSwCapsuleTriMeshColliders,
	StatTotalSwConvexConvexColliders,
	StatTotalSwConvexWheelColliders,
	StatTotalSwConvexPlaneColliders,
	StatTotalSwConvexHeightfieldColliders,
	StatTotalSwConvexTriMeshColliders,
	StatTotalSwWheelWheelColliders,
	StatTotalSwWheelPlaneColliders,
	StatTotalSwWheelHeightfieldColliders,
	StatTotalSwWheelTriMeshColliders,

	StatTotalHwBoxBoxColliders,
	StatTotalHwBoxSphereColliders,
	StatTotalHwBoxCapsuleColliders,
	StatTotalHwBoxConvexColliders,
	StatTotalHwBoxWheelColliders,
	StatTotalHwBoxPlaneColliders,
	StatTotalHwBoxHeightfieldColliders,
	StatTotalHwBoxTriMeshColliders,
	StatTotalHwSphereSphereColliders,
	StatTotalHwSphereCapsuleColliders,
	StatTotalHwSphereConvexColliders,
	StatTotalHwSphereWheelColliders,
	StatTotalHwSpherePlaneColliders,
	StatTotalHwSphereHeightfieldColliders,
	StatTotalHwSphereTriMeshColliders,
	StatTotalHwCapsuleCapsuleColliders,
	StatTotalHwCapsuleConvexColliders,
	StatTotalHwCapsuleWheelColliders,
	StatTotalHwCapsulePlaneColliders,
	StatTotalHwCapsuleHeightfieldColliders,
	StatTotalHwCapsuleTriMeshColliders,
	StatTotalHwConvexConvexColliders,
	StatTotalHwConvexWheelColliders,
	StatTotalHwConvexPlaneColliders,
	StatTotalHwConvexHeightfieldColliders,
	StatTotalHwConvexTriMeshColliders,
	StatTotalHwWheelWheelColliders,
	StatTotalHwWheelPlaneColliders,
	StatTotalHwWheelHeightfieldColliders,
	StatTotalHwWheelTriMeshColliders,

	StatTotalTriggers,

	StatSwBoxBoxTriggers,
	StatSwBoxSphereTriggers,
	StatSwBoxCapsuleTriggers,
	StatSwBoxConvexTriggers,
	StatSwBoxWheelTriggers,
	StatSwBoxPlaneTriggers,
	StatSwBoxHeightfieldTriggers,
	StatSwBoxTriMeshTriggers,
	StatSwSphereSphereTriggers,
	StatSwSphereCapsuleTriggers,
	StatSwSphereConvexTriggers,
	StatSwSphereWheelTriggers,
	StatSwSpherePlaneTriggers,
	StatSwSphereHeightfieldTriggers,
	StatSwSphereTriMeshTriggers,
	StatSwCapsuleCapsuleTriggers,
	StatSwCapsuleConvexTriggers,
	StatSwCapsuleWheelTriggers,
	StatSwCapsulePlaneTriggers,
	StatSwCapsuleHeightfieldTriggers,
	StatSwCapsuleTriMeshTriggers,
	StatSwConvexConvexTriggers,
	StatSwConvexWheelTriggers,
	StatSwConvexPlaneTriggers,
	StatSwConvexHeightfieldTriggers,
	StatSwConvexTriMeshTriggers,
	StatSwWheelWheelTriggers,
	StatSwWheelPlaneTriggers,
	StatSwWheelHeightfieldTriggers,
	StatSwWheelTriMeshTriggers,

	StatHwBoxBoxTriggers,
	StatHwBoxSphereTriggers,
	StatHwBoxCapsuleTriggers,
	StatHwBoxConvexTriggers,
	StatHwBoxWheelTriggers,
	StatHwBoxPlaneTriggers,
	StatHwBoxHeightfieldTriggers,
	StatHwBoxTriMeshTriggers,
	StatHwSphereSphereTriggers,
	StatHwSphereCapsuleTriggers,
	StatHwSphereConvexTriggers,
	StatHwSphereWheelTriggers,
	StatHwSpherePlaneTriggers,
	StatHwSphereHeightfieldTriggers,
	StatHwSphereTriMeshTriggers,
	StatHwCapsuleCapsuleTriggers,
	StatHwCapsuleConvexTriggers,
	StatHwCapsuleWheelTriggers,
	StatHwCapsulePlaneTriggers,
	StatHwCapsuleHeightfieldTriggers,
	StatHwCapsuleTriMeshTriggers,
	StatHwConvexConvexTriggers,
	StatHwConvexWheelTriggers,
	StatHwConvexPlaneTriggers,
	StatHwConvexHeightfieldTriggers,
	StatHwConvexTriMeshTriggers,
	StatHwWheelWheelTriggers,
	StatHwWheelPlaneTriggers,
	StatHwWheelHeightfieldTriggers,
	StatHwWheelTriMeshTriggers,

	StatTotalMeshPageInstances,
	StatMappedMeshPageInstances,
	StatAutoPageMappings,
	StatAutoPageUnmappings,
	StatFailedPageMappings,

	StatTotalIslands,

	StatActiveJoints,
	StatTotalJoints,
	StatDeadJoints,
	StatActiveD6Joints,
	StatTotalD6Joints,
	//StatProjectedD6Joints,
	StatActiveSphericalJoints,
	StatTotalSphericalJoints,
	//StatProjectedSphericalJoints,
	StatActiveRevoluteJoints,
	StatTotalRevoluteJoints,
	//StatProjectedRevoluteJoints,
	StatActiveCylindricalJoints,
	StatTotalCylindricalJoints,
	StatActiveDistanceJoints,
	StatTotalDistanceJoints,
	StatActiveFixedJoints,
	StatTotalFixedJoints,
	StatActivePointInPlaneJoints,
	StatTotalPointInPlaneJoints,
	StatActivePointOnLineJoints,
	StatTotalPointOnLineJoints,
	StatActivePrismaticJoints,
	StatTotalPrismaticJoints,
	StatActivePulleyJoints,
	StatTotalPulleyJoints,

	StatTotalRaycasts,
	StatTotalOverlapTests,
	StatTotalSweepTests,

	StatTotalFluidEmitters,
	//StatActiveFluids,
	StatTotalFluids,
	StatActiveFluidParticles,
	StatTotalFluidParticles,
	StatTotalFluidPackets,

	//StatFluidBoxInteractions,
	//StatFluidSphereInteractions,
	//StatFluidCapsuleInteractions,
	//StatFluidConvexInteractions,
	//StatFluidPlaneInteractions,
	//StatFluidHeightfieldInteractions,
	//StatFluidTriMeshInteractions,

	StatActiveCloths,
	StatTotalCloths,
	StatActiveTearableClothPieces,
	StatTotalTearableClothPieces,
	//StatActiveClothConstraints,
	//StatTotalClothConstraints,
	StatActiveClothVertices,
	StatTotalClothVertices,
	StatActiveAttachedClothVertices,
	StatTotalAttachedClothVertices,

	StatTotalForceFields,
	StatTotalForceFieldShapes,
	StatTotalBoxForceFieldShapes,
	StatTotalSphereForceFieldShapes,
	StatTotalCapsuleForceFieldShapes,
	StatTotalConvexForceFieldShapes,
	StatTotalForceFieldShapeGroups,
	StatTotalForceFieldOverlaps,
	StatTotalForceFieldRbOverlaps,
	StatTotalForceFieldFluidOverlaps,
	StatTotalForceFieldClothOverlaps,
	StatTotalForceFieldSoftBodyOverlaps,
	StatTotalForceFieldLinearKernels,
	StatActiveForceFieldLinearKernels,
	StatActiveForceFieldCustomKernels,

	StatWarnConvexShapesIgnored,
	StatWarnClothShapesDropped,
	StatWarnAxisConstraintsFailed,
	StatWarnJointDrivesIgnored,
	StatWarnPacketLimitedFluids,
	StatWarnHeightfieldIndicesDropped,
	StatWarnShapeMirrorFailed,
	StatWarnBodyMirrorFailed,

	NumStats //<! Not a statistic; represents the total number of statistics
};

NX_INLINE SceneStatisticEnum getJointStatType(NxJointType type, bool activeJoint)
{
	switch (type)
	{
	case NX_JOINT_CYLINDRICAL: return activeJoint ? StatActiveCylindricalJoints : StatTotalCylindricalJoints;
	case NX_JOINT_D6: return activeJoint ? StatActiveD6Joints : StatTotalD6Joints;
	case NX_JOINT_DISTANCE: return activeJoint ? StatActiveDistanceJoints : StatTotalDistanceJoints;
	case NX_JOINT_FIXED: return activeJoint ? StatActiveFixedJoints : StatTotalFixedJoints;
	case NX_JOINT_POINT_IN_PLANE: return activeJoint ? StatActivePointInPlaneJoints : StatTotalPointInPlaneJoints;
	case NX_JOINT_POINT_ON_LINE: return activeJoint ? StatActivePointOnLineJoints : StatTotalPointOnLineJoints;
	case NX_JOINT_PRISMATIC: return activeJoint ? StatActivePrismaticJoints : StatTotalPrismaticJoints;
	case NX_JOINT_PULLEY: return activeJoint ? StatActivePulleyJoints : StatTotalPulleyJoints;
	case NX_JOINT_REVOLUTE: return activeJoint ? StatActiveRevoluteJoints : StatTotalRevoluteJoints;
	default: return activeJoint ? StatActiveSphericalJoints : StatTotalSphericalJoints;
	}
}
#endif
