#ifndef __PHYSX_CELL_SDK_H__
#define __PHYSX_CELL_SDK_H__

#define PHYSX_CELL_SDK_VERSION			0x440001

#define PHYSX_CELL_TOOLCHAIN_VERSION		0x420001

#define PHYSX_CELL_SDK_VERSION_HEADER		0x440001

#endif // __PHYSX_CELL_SDK_H__
